language: elixir
elixir:
  - 1.3
otp_release:
  - 18.2.1
sudo: false
addons:
  postgresql: '9.4' # Use postgres 9.4 because Travis does not support 9.5 yet apparently
before_script:
  # Create the test database
  - psql -c 'create database peepchat_test;' -U postgres
